///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADS_start
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ADS_startRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("09521d48-2e8b-451f-ba27-57dec2960a58")]
    public partial class ADS_startRepository : RepoGenBaseFolder
    {
        static ADS_startRepository instance = new ADS_startRepository();
        ADS_startRepositoryFolders.LicenseForAquaDataStudioAppFolder _licenseforaquadatastudio;
        ADS_startRepositoryFolders.AquaDataStudioEvaluationAppFolder _aquadatastudioevaluation;

        /// <summary>
        /// Gets the singleton class instance representing the ADS_startRepository element repository.
        /// </summary>
        [RepositoryFolder("09521d48-2e8b-451f-ba27-57dec2960a58")]
        public static ADS_startRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ADS_startRepository() 
            : base("ADS_startRepository", "/", null, 0, false, "09521d48-2e8b-451f-ba27-57dec2960a58", ".\\RepositoryImages\\ADS_startRepository09521d48.rximgres")
        {
            _licenseforaquadatastudio = new ADS_startRepositoryFolders.LicenseForAquaDataStudioAppFolder(this);
            _aquadatastudioevaluation = new ADS_startRepositoryFolders.AquaDataStudioEvaluationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("09521d48-2e8b-451f-ba27-57dec2960a58")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LicenseForAquaDataStudio folder.
        /// </summary>
        [RepositoryFolder("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
        public virtual ADS_startRepositoryFolders.LicenseForAquaDataStudioAppFolder LicenseForAquaDataStudio
        {
            get { return _licenseforaquadatastudio; }
        }

        /// <summary>
        /// The AquaDataStudioEvaluation folder.
        /// </summary>
        [RepositoryFolder("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
        public virtual ADS_startRepositoryFolders.AquaDataStudioEvaluationAppFolder AquaDataStudioEvaluation
        {
            get { return _aquadatastudioevaluation; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ADS_startRepositoryFolders
    {
        /// <summary>
        /// The LicenseForAquaDataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
        public partial class LicenseForAquaDataStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _licenseforaquadatastudioInfo;
            RepoItemInfo _evaluateInfo;
            RepoItemInfo _evaluationiwouldliketorequesta1Info;

            /// <summary>
            /// Creates a new LicenseForAquaDataStudio  folder.
            /// </summary>
            public LicenseForAquaDataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LicenseForAquaDataStudio", "/form[@title>'License for Aqua Data Stu']", parentFolder, 30000, null, false, "10dc2930-1f3b-4ee4-9f04-c97c260319fc", "")
            {
                _licenseforaquadatastudioInfo = new RepoItemInfo(this, "LicenseForAquaDataStudio", "titlebar[@accessiblerole='TitleBar']", 30000, null, "e99ad039-0823-4862-9394-de44ea2dfd00");
                _evaluateInfo = new RepoItemInfo(this, "Evaluate", "container[2]/container[@name='fyG']//button[@name='fyo']", 30000, null, "187f23b6-7f6f-4a3f-9bea-4848000fe6d8");
                _evaluationiwouldliketorequesta1Info = new RepoItemInfo(this, "EvaluationIWouldLikeToRequestA1", "container[1]/?/?/radiobutton[@name='fyI']", 30000, null, "9365f044-54a3-43a8-a79d-31c13afa2d79");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LicenseForAquaDataStudio item.
            /// </summary>
            [RepositoryItem("e99ad039-0823-4862-9394-de44ea2dfd00")]
            public virtual Ranorex.TitleBar LicenseForAquaDataStudio
            {
                get
                {
                    return _licenseforaquadatastudioInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The LicenseForAquaDataStudio item info.
            /// </summary>
            [RepositoryItemInfo("e99ad039-0823-4862-9394-de44ea2dfd00")]
            public virtual RepoItemInfo LicenseForAquaDataStudioInfo
            {
                get
                {
                    return _licenseforaquadatastudioInfo;
                }
            }

            /// <summary>
            /// The Evaluate item.
            /// </summary>
            [RepositoryItem("187f23b6-7f6f-4a3f-9bea-4848000fe6d8")]
            public virtual Ranorex.Button Evaluate
            {
                get
                {
                    return _evaluateInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Evaluate item info.
            /// </summary>
            [RepositoryItemInfo("187f23b6-7f6f-4a3f-9bea-4848000fe6d8")]
            public virtual RepoItemInfo EvaluateInfo
            {
                get
                {
                    return _evaluateInfo;
                }
            }

            /// <summary>
            /// The EvaluationIWouldLikeToRequestA1 item.
            /// </summary>
            [RepositoryItem("9365f044-54a3-43a8-a79d-31c13afa2d79")]
            public virtual Ranorex.RadioButton EvaluationIWouldLikeToRequestA1
            {
                get
                {
                    return _evaluationiwouldliketorequesta1Info.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The EvaluationIWouldLikeToRequestA1 item info.
            /// </summary>
            [RepositoryItemInfo("9365f044-54a3-43a8-a79d-31c13afa2d79")]
            public virtual RepoItemInfo EvaluationIWouldLikeToRequestA1Info
            {
                get
                {
                    return _evaluationiwouldliketorequesta1Info;
                }
            }
        }

        /// <summary>
        /// The AquaDataStudioEvaluationAppFolder folder.
        /// </summary>
        [RepositoryFolder("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
        public partial class AquaDataStudioEvaluationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aquadatastudioevaluationInfo;

            /// <summary>
            /// Creates a new AquaDataStudioEvaluation  folder.
            /// </summary>
            public AquaDataStudioEvaluationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AquaDataStudioEvaluation", "/form[@title>'Aqua Data Studio - [Evalu']", parentFolder, 30000, null, false, "2cce129c-63ba-4d14-8126-6d1c4f35948d", "")
            {
                _aquadatastudioevaluationInfo = new RepoItemInfo(this, "AquaDataStudioEvaluation", "titlebar[@accessiblerole='TitleBar']", 30000, null, "905a42f9-8c43-4f69-bf97-5202952990bf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AquaDataStudioEvaluation item.
            /// </summary>
            [RepositoryItem("905a42f9-8c43-4f69-bf97-5202952990bf")]
            public virtual Ranorex.TitleBar AquaDataStudioEvaluation
            {
                get
                {
                    return _aquadatastudioevaluationInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The AquaDataStudioEvaluation item info.
            /// </summary>
            [RepositoryItemInfo("905a42f9-8c43-4f69-bf97-5202952990bf")]
            public virtual RepoItemInfo AquaDataStudioEvaluationInfo
            {
                get
                {
                    return _aquadatastudioevaluationInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
