///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADS_start
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ADS_startRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("09521d48-2e8b-451f-ba27-57dec2960a58")]
    public partial class ADS_startRepository : RepoGenBaseFolder
    {
        static ADS_startRepository instance = new ADS_startRepository();
        ADS_startRepositoryFolders.LicenseForAquaDataStudioAppFolder _licenseforaquadatastudio;
        ADS_startRepositoryFolders.AquaDataStudioEvaluationAppFolder _aquadatastudioevaluation;
        ADS_startRepositoryFolders.DatastudioAppFolder _datastudio;

        /// <summary>
        /// Gets the singleton class instance representing the ADS_startRepository element repository.
        /// </summary>
        [RepositoryFolder("09521d48-2e8b-451f-ba27-57dec2960a58")]
        public static ADS_startRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ADS_startRepository() 
            : base("ADS_startRepository", "/", null, 0, false, "09521d48-2e8b-451f-ba27-57dec2960a58", ".\\RepositoryImages\\ADS_startRepository09521d48.rximgres")
        {
            _licenseforaquadatastudio = new ADS_startRepositoryFolders.LicenseForAquaDataStudioAppFolder(this);
            _aquadatastudioevaluation = new ADS_startRepositoryFolders.AquaDataStudioEvaluationAppFolder(this);
            _datastudio = new ADS_startRepositoryFolders.DatastudioAppFolder(this);
        }

#region Variables

        string _srTypeEle = "MS SQL Server";

        /// <summary>
        /// Gets or sets the value of variable srTypeEle.
        /// </summary>
        [TestVariable("e36a9491-016d-4170-ab94-6b2333a199fd")]
        public string srTypeEle
        {
            get { return _srTypeEle; }
            set { _srTypeEle = value; }
        }

        string _WindowsAuthTypeRepo = "Windows Authentication";

        /// <summary>
        /// Gets or sets the value of variable WindowsAuthTypeRepo.
        /// </summary>
        [TestVariable("efcc0d3f-cc81-4ccb-8c68-81a82aa4b4e0")]
        public string WindowsAuthTypeRepo
        {
            get { return _WindowsAuthTypeRepo; }
            set { _WindowsAuthTypeRepo = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("09521d48-2e8b-451f-ba27-57dec2960a58")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LicenseForAquaDataStudio folder.
        /// </summary>
        [RepositoryFolder("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
        public virtual ADS_startRepositoryFolders.LicenseForAquaDataStudioAppFolder LicenseForAquaDataStudio
        {
            get { return _licenseforaquadatastudio; }
        }

        /// <summary>
        /// The AquaDataStudioEvaluation folder.
        /// </summary>
        [RepositoryFolder("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
        public virtual ADS_startRepositoryFolders.AquaDataStudioEvaluationAppFolder AquaDataStudioEvaluation
        {
            get { return _aquadatastudioevaluation; }
        }

        /// <summary>
        /// The Datastudio folder.
        /// </summary>
        [RepositoryFolder("cf4fbc79-3679-4fb2-8ac2-094be21b7391")]
        public virtual ADS_startRepositoryFolders.DatastudioAppFolder Datastudio
        {
            get { return _datastudio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ADS_startRepositoryFolders
    {
        /// <summary>
        /// The LicenseForAquaDataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
        public partial class LicenseForAquaDataStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _licenseforaquadatastudioInfo;
            RepoItemInfo _evaluateInfo;
            RepoItemInfo _evaluationiwouldliketorequesta1Info;

            /// <summary>
            /// Creates a new LicenseForAquaDataStudio  folder.
            /// </summary>
            public LicenseForAquaDataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LicenseForAquaDataStudio", "/form[@title>'License for Aqua Data Stu']", parentFolder, 30000, null, false, "10dc2930-1f3b-4ee4-9f04-c97c260319fc", "")
            {
                _licenseforaquadatastudioInfo = new RepoItemInfo(this, "LicenseForAquaDataStudio", "titlebar[@accessiblerole='TitleBar']", 30000, null, "e99ad039-0823-4862-9394-de44ea2dfd00");
                _evaluateInfo = new RepoItemInfo(this, "Evaluate", "container[2]/container[@name='fyG']//button[@name='fyo']", 30000, null, "187f23b6-7f6f-4a3f-9bea-4848000fe6d8");
                _evaluationiwouldliketorequesta1Info = new RepoItemInfo(this, "EvaluationIWouldLikeToRequestA1", "container[1]/?/?/radiobutton[@name='fyI']", 30000, null, "9365f044-54a3-43a8-a79d-31c13afa2d79");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LicenseForAquaDataStudio item.
            /// </summary>
            [RepositoryItem("e99ad039-0823-4862-9394-de44ea2dfd00")]
            public virtual Ranorex.TitleBar LicenseForAquaDataStudio
            {
                get
                {
                    return _licenseforaquadatastudioInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The LicenseForAquaDataStudio item info.
            /// </summary>
            [RepositoryItemInfo("e99ad039-0823-4862-9394-de44ea2dfd00")]
            public virtual RepoItemInfo LicenseForAquaDataStudioInfo
            {
                get
                {
                    return _licenseforaquadatastudioInfo;
                }
            }

            /// <summary>
            /// The Evaluate item.
            /// </summary>
            [RepositoryItem("187f23b6-7f6f-4a3f-9bea-4848000fe6d8")]
            public virtual Ranorex.Button Evaluate
            {
                get
                {
                    return _evaluateInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Evaluate item info.
            /// </summary>
            [RepositoryItemInfo("187f23b6-7f6f-4a3f-9bea-4848000fe6d8")]
            public virtual RepoItemInfo EvaluateInfo
            {
                get
                {
                    return _evaluateInfo;
                }
            }

            /// <summary>
            /// The EvaluationIWouldLikeToRequestA1 item.
            /// </summary>
            [RepositoryItem("9365f044-54a3-43a8-a79d-31c13afa2d79")]
            public virtual Ranorex.RadioButton EvaluationIWouldLikeToRequestA1
            {
                get
                {
                    return _evaluationiwouldliketorequesta1Info.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The EvaluationIWouldLikeToRequestA1 item info.
            /// </summary>
            [RepositoryItemInfo("9365f044-54a3-43a8-a79d-31c13afa2d79")]
            public virtual RepoItemInfo EvaluationIWouldLikeToRequestA1Info
            {
                get
                {
                    return _evaluationiwouldliketorequesta1Info;
                }
            }
        }

        /// <summary>
        /// The AquaDataStudioEvaluationAppFolder folder.
        /// </summary>
        [RepositoryFolder("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
        public partial class AquaDataStudioEvaluationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aquadatastudioevaluationInfo;
            RepoItemInfo _databaseserverseleInfo;
            RepoItemInfo _newitemInfo;

            /// <summary>
            /// Creates a new AquaDataStudioEvaluation  folder.
            /// </summary>
            public AquaDataStudioEvaluationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AquaDataStudioEvaluation", "/form[@title>'Aqua Data Studio - [Evalu']", parentFolder, 30000, null, false, "2cce129c-63ba-4d14-8126-6d1c4f35948d", "")
            {
                _aquadatastudioevaluationInfo = new RepoItemInfo(this, "AquaDataStudioEvaluation", "titlebar[@accessiblerole='TitleBar']", 30000, null, "905a42f9-8c43-4f69-bf97-5202952990bf");
                _databaseserverseleInfo = new RepoItemInfo(this, "DatabaseServersEle", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='fLp']/?/?/treeitem[@text='Local Database Servers']", 30000, null, "134da088-e423-4baf-91a3-d7088f21cea7");
                _newitemInfo = new RepoItemInfo(this, "NewItem", "element", 30000, null, "c9cdd7df-9304-43f2-b484-8e6ff400ecfc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AquaDataStudioEvaluation item.
            /// </summary>
            [RepositoryItem("905a42f9-8c43-4f69-bf97-5202952990bf")]
            public virtual Ranorex.TitleBar AquaDataStudioEvaluation
            {
                get
                {
                    return _aquadatastudioevaluationInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The AquaDataStudioEvaluation item info.
            /// </summary>
            [RepositoryItemInfo("905a42f9-8c43-4f69-bf97-5202952990bf")]
            public virtual RepoItemInfo AquaDataStudioEvaluationInfo
            {
                get
                {
                    return _aquadatastudioevaluationInfo;
                }
            }

            /// <summary>
            /// The DatabaseServersEle item.
            /// </summary>
            [RepositoryItem("134da088-e423-4baf-91a3-d7088f21cea7")]
            public virtual Ranorex.TreeItem DatabaseServersEle
            {
                get
                {
                    return _databaseserverseleInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DatabaseServersEle item info.
            /// </summary>
            [RepositoryItemInfo("134da088-e423-4baf-91a3-d7088f21cea7")]
            public virtual RepoItemInfo DatabaseServersEleInfo
            {
                get
                {
                    return _databaseserverseleInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("c9cdd7df-9304-43f2-b484-8e6ff400ecfc")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("c9cdd7df-9304-43f2-b484-8e6ff400ecfc")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }
        }

        /// <summary>
        /// The DatastudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("cf4fbc79-3679-4fb2-8ac2-094be21b7391")]
        public partial class DatastudioAppFolder : RepoGenBaseFolder
        {
            ADS_startRepositoryFolders.ContainerFYsFolder _containerfys;
            ADS_startRepositoryFolders.ComboBoxListFolder _comboboxlist;
            ADS_startRepositoryFolders.JPanelFolder _jpanel;
            RepoItemInfo _registerservereleInfo;
            RepoItemInfo _registerservertitlebarformeleInfo;
            RepoItemInfo _testconnbtneleInfo;
            RepoItemInfo _saveserverregeleInfo;
            RepoItemInfo _closetestconneleInfo;
            RepoItemInfo _cancelInfo;
            RepoItemInfo _servertypelisteleInfo;
            RepoItemInfo _mssqldatabaseazureInfo;
            RepoItemInfo _mssqlservereleInfo;
            RepoItemInfo _containerfssInfo;
            RepoItemInfo _containerfxvInfo;
            RepoItemInfo _mountedscriptsInfo;

            /// <summary>
            /// Creates a new Datastudio  folder.
            /// </summary>
            public DatastudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio", "/form[@processname='datastudio']", parentFolder, 30000, null, false, "cf4fbc79-3679-4fb2-8ac2-094be21b7391", "")
            {
                _containerfys = new ADS_startRepositoryFolders.ContainerFYsFolder(this);
                _comboboxlist = new ADS_startRepositoryFolders.ComboBoxListFolder(this);
                _jpanel = new ADS_startRepositoryFolders.JPanelFolder(this);
                _registerservereleInfo = new RepoItemInfo(this, "RegisterServerEle", "?/?/menuitem[@text='Register Server']", 30000, null, "901d7c4b-ac71-4a8b-9fd8-ee893a8af108");
                _registerservertitlebarformeleInfo = new RepoItemInfo(this, "RegisterServerTitleBarFormEle", "titlebar[@accessiblerole='TitleBar']", 30000, null, "f51fcf82-8b96-4702-be12-733d436a525c");
                _testconnbtneleInfo = new RepoItemInfo(this, "TestConnBtnEle", "container[@type='Iꅟꎴꏁͦ7for']/?/?/button[@name='fYo']", 30000, null, "25849581-d360-4865-8b2e-5b0895c86adf");
                _saveserverregeleInfo = new RepoItemInfo(this, "SaveServerRegEle", "container[@type='Iꅟꎴꏁͦ7for']/?/?/button[@name='fxO']", 30000, null, "c8eb4347-55f9-499f-a71b-2a42c1d41100");
                _closetestconneleInfo = new RepoItemInfo(this, "CloseTestConnEle", "container[@type='JPanel']/container[@type='Iꅟꎴꏁͦ7for']//button[@name='defaultButton']", 30000, null, "bec9ae60-cd28-4dbf-b05b-e71a4ff48d21");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "container[@type='Iꅟꎴꏁͦ7for']/?/?/button[@name='fxP']", 30000, null, "78734b1f-45d5-4c12-8c34-aa7a84abd4a4");
                _servertypelisteleInfo = new RepoItemInfo(this, "serverTypeListEle", "?/?/container[@name='fXv']/?/?/container[@name='fXG']/?/?/list[@name='fXF']", 30000, null, "b74401b5-1bd8-4da7-9a52-7ba47100fa5d");
                _mssqldatabaseazureInfo = new RepoItemInfo(this, "MSSQLDatabaseAzure", "?/?/container[@name='fXv']/?/?/container[@name='fXG']/?/?/list[@name='fXF']/listitem[@text='MS SQL Database (Azure)']", 30000, null, "f284b8fb-17cc-43a0-be69-2170272ce3e3");
                _mssqlservereleInfo = new RepoItemInfo(this, "MSSQLServerEle", "?/?/container[@name='fXv']/?/?/container[@name='fXG']/?/?/list[@name='fXF']/listitem[@text=$srTypeEle]", 30000, null, "0a1120c9-65b7-4775-8751-edc78ec12dd2");
                _containerfssInfo = new RepoItemInfo(this, "ContainerFSs", "container[@name='fSs']", 30000, null, "64133332-55f6-4dea-990a-61e5366fbfe3");
                _containerfxvInfo = new RepoItemInfo(this, "ContainerFXv", "?/?/container[@name='fXv']", 30000, null, "452336e2-9f90-4a40-b4cb-47820d5c9767");
                _mountedscriptsInfo = new RepoItemInfo(this, "MountedScripts", "?/?/container[@name='fXv']/?/?/text[@caption='Mounted Scripts']", 30000, null, "1d99437a-3a4c-4874-8e78-5c901900689b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf4fbc79-3679-4fb2-8ac2-094be21b7391")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf4fbc79-3679-4fb2-8ac2-094be21b7391")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RegisterServerEle item.
            /// </summary>
            [RepositoryItem("901d7c4b-ac71-4a8b-9fd8-ee893a8af108")]
            public virtual Ranorex.MenuItem RegisterServerEle
            {
                get
                {
                    return _registerservereleInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The RegisterServerEle item info.
            /// </summary>
            [RepositoryItemInfo("901d7c4b-ac71-4a8b-9fd8-ee893a8af108")]
            public virtual RepoItemInfo RegisterServerEleInfo
            {
                get
                {
                    return _registerservereleInfo;
                }
            }

            /// <summary>
            /// The RegisterServerTitleBarFormEle item.
            /// </summary>
            [RepositoryItem("f51fcf82-8b96-4702-be12-733d436a525c")]
            public virtual Ranorex.TitleBar RegisterServerTitleBarFormEle
            {
                get
                {
                    return _registerservertitlebarformeleInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The RegisterServerTitleBarFormEle item info.
            /// </summary>
            [RepositoryItemInfo("f51fcf82-8b96-4702-be12-733d436a525c")]
            public virtual RepoItemInfo RegisterServerTitleBarFormEleInfo
            {
                get
                {
                    return _registerservertitlebarformeleInfo;
                }
            }

            /// <summary>
            /// The TestConnBtnEle item.
            /// </summary>
            [RepositoryItem("25849581-d360-4865-8b2e-5b0895c86adf")]
            public virtual Ranorex.Button TestConnBtnEle
            {
                get
                {
                    return _testconnbtneleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TestConnBtnEle item info.
            /// </summary>
            [RepositoryItemInfo("25849581-d360-4865-8b2e-5b0895c86adf")]
            public virtual RepoItemInfo TestConnBtnEleInfo
            {
                get
                {
                    return _testconnbtneleInfo;
                }
            }

            /// <summary>
            /// The SaveServerRegEle item.
            /// </summary>
            [RepositoryItem("c8eb4347-55f9-499f-a71b-2a42c1d41100")]
            public virtual Ranorex.Button SaveServerRegEle
            {
                get
                {
                    return _saveserverregeleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveServerRegEle item info.
            /// </summary>
            [RepositoryItemInfo("c8eb4347-55f9-499f-a71b-2a42c1d41100")]
            public virtual RepoItemInfo SaveServerRegEleInfo
            {
                get
                {
                    return _saveserverregeleInfo;
                }
            }

            /// <summary>
            /// The CloseTestConnEle item.
            /// </summary>
            [RepositoryItem("bec9ae60-cd28-4dbf-b05b-e71a4ff48d21")]
            public virtual Ranorex.Button CloseTestConnEle
            {
                get
                {
                    return _closetestconneleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseTestConnEle item info.
            /// </summary>
            [RepositoryItemInfo("bec9ae60-cd28-4dbf-b05b-e71a4ff48d21")]
            public virtual RepoItemInfo CloseTestConnEleInfo
            {
                get
                {
                    return _closetestconneleInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("78734b1f-45d5-4c12-8c34-aa7a84abd4a4")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("78734b1f-45d5-4c12-8c34-aa7a84abd4a4")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }

            /// <summary>
            /// The serverTypeListEle item.
            /// </summary>
            [RepositoryItem("b74401b5-1bd8-4da7-9a52-7ba47100fa5d")]
            public virtual Ranorex.List serverTypeListEle
            {
                get
                {
                    return _servertypelisteleInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The serverTypeListEle item info.
            /// </summary>
            [RepositoryItemInfo("b74401b5-1bd8-4da7-9a52-7ba47100fa5d")]
            public virtual RepoItemInfo serverTypeListEleInfo
            {
                get
                {
                    return _servertypelisteleInfo;
                }
            }

            /// <summary>
            /// The MSSQLDatabaseAzure item.
            /// </summary>
            [RepositoryItem("f284b8fb-17cc-43a0-be69-2170272ce3e3")]
            public virtual Ranorex.ListItem MSSQLDatabaseAzure
            {
                get
                {
                    return _mssqldatabaseazureInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The MSSQLDatabaseAzure item info.
            /// </summary>
            [RepositoryItemInfo("f284b8fb-17cc-43a0-be69-2170272ce3e3")]
            public virtual RepoItemInfo MSSQLDatabaseAzureInfo
            {
                get
                {
                    return _mssqldatabaseazureInfo;
                }
            }

            /// <summary>
            /// The MSSQLServerEle item.
            /// </summary>
            [RepositoryItem("0a1120c9-65b7-4775-8751-edc78ec12dd2")]
            public virtual Ranorex.ListItem MSSQLServerEle
            {
                get
                {
                    return _mssqlservereleInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The MSSQLServerEle item info.
            /// </summary>
            [RepositoryItemInfo("0a1120c9-65b7-4775-8751-edc78ec12dd2")]
            public virtual RepoItemInfo MSSQLServerEleInfo
            {
                get
                {
                    return _mssqlservereleInfo;
                }
            }

            /// <summary>
            /// The ContainerFSs item.
            /// </summary>
            [RepositoryItem("64133332-55f6-4dea-990a-61e5366fbfe3")]
            public virtual Ranorex.Container ContainerFSs
            {
                get
                {
                    return _containerfssInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerFSs item info.
            /// </summary>
            [RepositoryItemInfo("64133332-55f6-4dea-990a-61e5366fbfe3")]
            public virtual RepoItemInfo ContainerFSsInfo
            {
                get
                {
                    return _containerfssInfo;
                }
            }

            /// <summary>
            /// The ContainerFXv item.
            /// </summary>
            [RepositoryItem("452336e2-9f90-4a40-b4cb-47820d5c9767")]
            public virtual Ranorex.Container ContainerFXv
            {
                get
                {
                    return _containerfxvInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerFXv item info.
            /// </summary>
            [RepositoryItemInfo("452336e2-9f90-4a40-b4cb-47820d5c9767")]
            public virtual RepoItemInfo ContainerFXvInfo
            {
                get
                {
                    return _containerfxvInfo;
                }
            }

            /// <summary>
            /// The MountedScripts item.
            /// </summary>
            [RepositoryItem("1d99437a-3a4c-4874-8e78-5c901900689b")]
            public virtual Ranorex.Text MountedScripts
            {
                get
                {
                    return _mountedscriptsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MountedScripts item info.
            /// </summary>
            [RepositoryItemInfo("1d99437a-3a4c-4874-8e78-5c901900689b")]
            public virtual RepoItemInfo MountedScriptsInfo
            {
                get
                {
                    return _mountedscriptsInfo;
                }
            }

            /// <summary>
            /// The ContainerFYs folder.
            /// </summary>
            [RepositoryFolder("5ce8ad34-b2a1-4077-bd81-84cf5b154ccf")]
            public virtual ADS_startRepositoryFolders.ContainerFYsFolder ContainerFYs
            {
                get { return _containerfys; }
            }

            /// <summary>
            /// The ComboBoxList folder.
            /// </summary>
            [RepositoryFolder("341885ab-20f8-43d1-aa7c-9792e2c05866")]
            public virtual ADS_startRepositoryFolders.ComboBoxListFolder ComboBoxList
            {
                get { return _comboboxlist; }
            }

            /// <summary>
            /// The JPanel folder.
            /// </summary>
            [RepositoryFolder("da1c9984-be94-4ea0-a3e1-8db07d76f1f9")]
            public virtual ADS_startRepositoryFolders.JPanelFolder JPanel
            {
                get { return _jpanel; }
            }
        }

        /// <summary>
        /// The ContainerFYsFolder folder.
        /// </summary>
        [RepositoryFolder("5ce8ad34-b2a1-4077-bd81-84cf5b154ccf")]
        public partial class ContainerFYsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _servernameeleInfo;
            RepoItemInfo _hostnameele1Info;
            RepoItemInfo _comboauthtypeeleInfo;
            RepoItemInfo _loginnameInfo;
            RepoItemInfo _loginpwdeleInfo;
            RepoItemInfo _logintxteleInfo;
            RepoItemInfo _drivecombodropbtneleInfo;
            RepoItemInfo _combodrivereleInfo;
            RepoItemInfo _jtextfield1Info;
            RepoItemInfo _textecInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _jtextfield2Info;
            RepoItemInfo _hostnameeleInfo;
            RepoItemInfo _jpanelInfo;

            /// <summary>
            /// Creates a new ContainerFYs  folder.
            /// </summary>
            public ContainerFYsFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerFYs", "container[@name='fSs']/container[@name='fXv']/?/?/container[@name='fYs']", parentFolder, 30000, null, false, "5ce8ad34-b2a1-4077-bd81-84cf5b154ccf", "")
            {
                _servernameeleInfo = new RepoItemInfo(this, "serverNameEle", ".//container[@name='gcl']/?/?/text[@name='ec']", 30000, null, "283203c7-9039-422c-8288-02ca3f152992");
                _hostnameele1Info = new RepoItemInfo(this, "hostNameEle1", ".//container[@name='gfT']/text[@caption>' host OR host\\named_insta']", 30000, null, "a3db2383-3fda-4f0d-a304-6bdfa79bac3c");
                _comboauthtypeeleInfo = new RepoItemInfo(this, "ComboAuthTypeEle", ".//container[@type='Pꈘᜬᛌᝊtransient5']/?/?/combobox[@name='eXC']", 30000, null, "c3cec3c5-dc17-4c1d-b8af-a5582580e068");
                _loginnameInfo = new RepoItemInfo(this, "LoginName", ".//container[@type='Pꈘᜬᛌᝊtransient5']/?/?/text[@caption='Login Name:']", 30000, null, "558e00ad-b5f4-4de9-9b19-b74899689dff");
                _loginpwdeleInfo = new RepoItemInfo(this, "LoginPwdEle", ".//container[@type='Pꈘᜬᛌᝊtransient5']/?/?/text[@type='JPasswordField']", 30000, null, "4f9346da-db00-451c-ae3b-49ea11626fc4");
                _logintxteleInfo = new RepoItemInfo(this, "LoginTxtEle", ".//container[@type='Pꈘᜬᛌᝊtransient5']/?/?/text[@type='JTextField']", 30000, null, "0e4df0ae-1d62-4eca-86db-5aec59a7857f");
                _drivecombodropbtneleInfo = new RepoItemInfo(this, "driveComboDropBtnEle", ".//container[@name='gfP']/?/?/combobox[@name='gfH']/button[@text='']", 30000, null, "05cd800d-b6ed-4909-9e9c-841fd0b9e6ef");
                _combodrivereleInfo = new RepoItemInfo(this, "comboDriverEle", ".//container[@name='gfP']/?/?/combobox[@name='gfH']", 30000, null, "63f55ca4-4abc-46c4-96f5-35c52925373a");
                _jtextfield1Info = new RepoItemInfo(this, "JTextField1", ".//container[@type='z⠰ꆁꉊꂐ']/?/?/text[@type='JTextField']", 30000, null, "7e5f9607-6e54-44b1-b172-41b9a3877ac1");
                _textecInfo = new RepoItemInfo(this, "TextEc", ".//container[@type='N⣏ꌢ̤ꅒfor']/?/?/text[@name='ec']", 30000, null, "5425c332-2f85-4618-afa7-075df9de85d6");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//container[@type='Pꈘᜬᛌᝊtransient5']/?/?/text[@caption='Password:']", 30000, null, "0a07913f-c104-4a3a-9a0c-3104a320c8ab");
                _jtextfield2Info = new RepoItemInfo(this, "JTextField2", ".//container[@type='n⠩ꑽꃒꑖtransient8']/?/?/text[@type='JTextField']", 30000, null, "2268c5da-5caf-4db0-81d0-4f2bfcde18c0");
                _hostnameeleInfo = new RepoItemInfo(this, "hostNameEle", ".//container[@name='gfT']/text[@name='_actualComponent']", 30000, null, "babc60d0-c366-4a1d-93ce-0f01c99858bf");
                _jpanelInfo = new RepoItemInfo(this, "JPanel", "?/?/container[@type='JPanel']", 30000, null, "2d2f29b9-11c6-44ec-b377-03ca982572d9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5ce8ad34-b2a1-4077-bd81-84cf5b154ccf")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5ce8ad34-b2a1-4077-bd81-84cf5b154ccf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The serverNameEle item.
            /// </summary>
            [RepositoryItem("283203c7-9039-422c-8288-02ca3f152992")]
            public virtual Ranorex.Text serverNameEle
            {
                get
                {
                    return _servernameeleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The serverNameEle item info.
            /// </summary>
            [RepositoryItemInfo("283203c7-9039-422c-8288-02ca3f152992")]
            public virtual RepoItemInfo serverNameEleInfo
            {
                get
                {
                    return _servernameeleInfo;
                }
            }

            /// <summary>
            /// The hostNameEle1 item.
            /// </summary>
            [RepositoryItem("a3db2383-3fda-4f0d-a304-6bdfa79bac3c")]
            public virtual Ranorex.Text hostNameEle1
            {
                get
                {
                    return _hostnameele1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The hostNameEle1 item info.
            /// </summary>
            [RepositoryItemInfo("a3db2383-3fda-4f0d-a304-6bdfa79bac3c")]
            public virtual RepoItemInfo hostNameEle1Info
            {
                get
                {
                    return _hostnameele1Info;
                }
            }

            /// <summary>
            /// The ComboAuthTypeEle item.
            /// </summary>
            [RepositoryItem("c3cec3c5-dc17-4c1d-b8af-a5582580e068")]
            public virtual Ranorex.ComboBox ComboAuthTypeEle
            {
                get
                {
                    return _comboauthtypeeleInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboAuthTypeEle item info.
            /// </summary>
            [RepositoryItemInfo("c3cec3c5-dc17-4c1d-b8af-a5582580e068")]
            public virtual RepoItemInfo ComboAuthTypeEleInfo
            {
                get
                {
                    return _comboauthtypeeleInfo;
                }
            }

            /// <summary>
            /// The LoginName item.
            /// </summary>
            [RepositoryItem("558e00ad-b5f4-4de9-9b19-b74899689dff")]
            public virtual Ranorex.Text LoginName
            {
                get
                {
                    return _loginnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LoginName item info.
            /// </summary>
            [RepositoryItemInfo("558e00ad-b5f4-4de9-9b19-b74899689dff")]
            public virtual RepoItemInfo LoginNameInfo
            {
                get
                {
                    return _loginnameInfo;
                }
            }

            /// <summary>
            /// The LoginPwdEle item.
            /// </summary>
            [RepositoryItem("4f9346da-db00-451c-ae3b-49ea11626fc4")]
            public virtual Ranorex.Text LoginPwdEle
            {
                get
                {
                    return _loginpwdeleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LoginPwdEle item info.
            /// </summary>
            [RepositoryItemInfo("4f9346da-db00-451c-ae3b-49ea11626fc4")]
            public virtual RepoItemInfo LoginPwdEleInfo
            {
                get
                {
                    return _loginpwdeleInfo;
                }
            }

            /// <summary>
            /// The LoginTxtEle item.
            /// </summary>
            [RepositoryItem("0e4df0ae-1d62-4eca-86db-5aec59a7857f")]
            public virtual Ranorex.Text LoginTxtEle
            {
                get
                {
                    return _logintxteleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LoginTxtEle item info.
            /// </summary>
            [RepositoryItemInfo("0e4df0ae-1d62-4eca-86db-5aec59a7857f")]
            public virtual RepoItemInfo LoginTxtEleInfo
            {
                get
                {
                    return _logintxteleInfo;
                }
            }

            /// <summary>
            /// The driveComboDropBtnEle item.
            /// </summary>
            [RepositoryItem("05cd800d-b6ed-4909-9e9c-841fd0b9e6ef")]
            public virtual Ranorex.Button driveComboDropBtnEle
            {
                get
                {
                    return _drivecombodropbtneleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The driveComboDropBtnEle item info.
            /// </summary>
            [RepositoryItemInfo("05cd800d-b6ed-4909-9e9c-841fd0b9e6ef")]
            public virtual RepoItemInfo driveComboDropBtnEleInfo
            {
                get
                {
                    return _drivecombodropbtneleInfo;
                }
            }

            /// <summary>
            /// The comboDriverEle item.
            /// </summary>
            [RepositoryItem("63f55ca4-4abc-46c4-96f5-35c52925373a")]
            public virtual Ranorex.ComboBox comboDriverEle
            {
                get
                {
                    return _combodrivereleInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The comboDriverEle item info.
            /// </summary>
            [RepositoryItemInfo("63f55ca4-4abc-46c4-96f5-35c52925373a")]
            public virtual RepoItemInfo comboDriverEleInfo
            {
                get
                {
                    return _combodrivereleInfo;
                }
            }

            /// <summary>
            /// The JTextField1 item.
            /// </summary>
            [RepositoryItem("7e5f9607-6e54-44b1-b172-41b9a3877ac1")]
            public virtual Ranorex.Text JTextField1
            {
                get
                {
                    return _jtextfield1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The JTextField1 item info.
            /// </summary>
            [RepositoryItemInfo("7e5f9607-6e54-44b1-b172-41b9a3877ac1")]
            public virtual RepoItemInfo JTextField1Info
            {
                get
                {
                    return _jtextfield1Info;
                }
            }

            /// <summary>
            /// The TextEc item.
            /// </summary>
            [RepositoryItem("5425c332-2f85-4618-afa7-075df9de85d6")]
            public virtual Ranorex.Text TextEc
            {
                get
                {
                    return _textecInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextEc item info.
            /// </summary>
            [RepositoryItemInfo("5425c332-2f85-4618-afa7-075df9de85d6")]
            public virtual RepoItemInfo TextEcInfo
            {
                get
                {
                    return _textecInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("0a07913f-c104-4a3a-9a0c-3104a320c8ab")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("0a07913f-c104-4a3a-9a0c-3104a320c8ab")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The JTextField2 item.
            /// </summary>
            [RepositoryItem("2268c5da-5caf-4db0-81d0-4f2bfcde18c0")]
            public virtual Ranorex.Text JTextField2
            {
                get
                {
                    return _jtextfield2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The JTextField2 item info.
            /// </summary>
            [RepositoryItemInfo("2268c5da-5caf-4db0-81d0-4f2bfcde18c0")]
            public virtual RepoItemInfo JTextField2Info
            {
                get
                {
                    return _jtextfield2Info;
                }
            }

            /// <summary>
            /// The hostNameEle item.
            /// </summary>
            [RepositoryItem("babc60d0-c366-4a1d-93ce-0f01c99858bf")]
            public virtual Ranorex.Text hostNameEle
            {
                get
                {
                    return _hostnameeleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The hostNameEle item info.
            /// </summary>
            [RepositoryItemInfo("babc60d0-c366-4a1d-93ce-0f01c99858bf")]
            public virtual RepoItemInfo hostNameEleInfo
            {
                get
                {
                    return _hostnameeleInfo;
                }
            }

            /// <summary>
            /// The JPanel item.
            /// </summary>
            [RepositoryItem("2d2f29b9-11c6-44ec-b377-03ca982572d9")]
            public virtual Ranorex.Container JPanel
            {
                get
                {
                    return _jpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The JPanel item info.
            /// </summary>
            [RepositoryItemInfo("2d2f29b9-11c6-44ec-b377-03ca982572d9")]
            public virtual RepoItemInfo JPanelInfo
            {
                get
                {
                    return _jpanelInfo;
                }
            }
        }

        /// <summary>
        /// The ComboBoxListFolder folder.
        /// </summary>
        [RepositoryFolder("341885ab-20f8-43d1-aa7c-9792e2c05866")]
        public partial class ComboBoxListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _microsofteleInfo;
            RepoItemInfo _windowssinglesignonInfo;
            RepoItemInfo _jtdsdrivereleInfo;
            RepoItemInfo _authtypeeleInfo;

            /// <summary>
            /// Creates a new ComboBoxList  folder.
            /// </summary>
            public ComboBoxListFolder(RepoGenBaseFolder parentFolder) :
                    base("ComboBoxList", ".//container[@name='viewport']/list[@name='ComboBox.list']", parentFolder, 30000, null, false, "341885ab-20f8-43d1-aa7c-9792e2c05866", "")
            {
                _microsofteleInfo = new RepoItemInfo(this, "MicrosoftEle", "listitem[@text='Microsoft']", 30000, null, "4608a88a-1037-478b-b052-a693b7ed64d8");
                _windowssinglesignonInfo = new RepoItemInfo(this, "WindowsSingleSignOn", "listitem[@text='Windows Single Sign-On']", 30000, null, "a036c9ed-afed-482e-8631-d72cadd0991b");
                _jtdsdrivereleInfo = new RepoItemInfo(this, "JTDSDriverEle", "listitem[@text='jTDS']", 30000, null, "d13b784d-77e1-4524-b36a-c092a9174f31");
                _authtypeeleInfo = new RepoItemInfo(this, "AuthTypeEle", "listitem[@text=$WindowsAuthTypeRepo]", 30000, null, "1a4048a2-a48f-41c4-b9c8-943fe2d2e450");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("341885ab-20f8-43d1-aa7c-9792e2c05866")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("341885ab-20f8-43d1-aa7c-9792e2c05866")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MicrosoftEle item.
            /// </summary>
            [RepositoryItem("4608a88a-1037-478b-b052-a693b7ed64d8")]
            public virtual Ranorex.ListItem MicrosoftEle
            {
                get
                {
                    return _microsofteleInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The MicrosoftEle item info.
            /// </summary>
            [RepositoryItemInfo("4608a88a-1037-478b-b052-a693b7ed64d8")]
            public virtual RepoItemInfo MicrosoftEleInfo
            {
                get
                {
                    return _microsofteleInfo;
                }
            }

            /// <summary>
            /// The WindowsSingleSignOn item.
            /// </summary>
            [RepositoryItem("a036c9ed-afed-482e-8631-d72cadd0991b")]
            public virtual Ranorex.ListItem WindowsSingleSignOn
            {
                get
                {
                    return _windowssinglesignonInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The WindowsSingleSignOn item info.
            /// </summary>
            [RepositoryItemInfo("a036c9ed-afed-482e-8631-d72cadd0991b")]
            public virtual RepoItemInfo WindowsSingleSignOnInfo
            {
                get
                {
                    return _windowssinglesignonInfo;
                }
            }

            /// <summary>
            /// The JTDSDriverEle item.
            /// </summary>
            [RepositoryItem("d13b784d-77e1-4524-b36a-c092a9174f31")]
            public virtual Ranorex.ListItem JTDSDriverEle
            {
                get
                {
                    return _jtdsdrivereleInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The JTDSDriverEle item info.
            /// </summary>
            [RepositoryItemInfo("d13b784d-77e1-4524-b36a-c092a9174f31")]
            public virtual RepoItemInfo JTDSDriverEleInfo
            {
                get
                {
                    return _jtdsdrivereleInfo;
                }
            }

            /// <summary>
            /// The AuthTypeEle item.
            /// </summary>
            [RepositoryItem("1a4048a2-a48f-41c4-b9c8-943fe2d2e450")]
            public virtual Ranorex.ListItem AuthTypeEle
            {
                get
                {
                    return _authtypeeleInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The AuthTypeEle item info.
            /// </summary>
            [RepositoryItemInfo("1a4048a2-a48f-41c4-b9c8-943fe2d2e450")]
            public virtual RepoItemInfo AuthTypeEleInfo
            {
                get
                {
                    return _authtypeeleInfo;
                }
            }
        }

        /// <summary>
        /// The JPanelFolder folder.
        /// </summary>
        [RepositoryFolder("da1c9984-be94-4ea0-a3e1-8db07d76f1f9")]
        public partial class JPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _successconntodbeleInfo;
            RepoItemInfo _yourserverisacceptingsocketconnectiInfo;
            RepoItemInfo _successfullyconnectedtodatabaseusingInfo;

            /// <summary>
            /// Creates a new JPanel  folder.
            /// </summary>
            public JPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("JPanel", "container[@type='JPanel']", parentFolder, 30000, null, false, "da1c9984-be94-4ea0-a3e1-8db07d76f1f9", "")
            {
                _successconntodbeleInfo = new RepoItemInfo(this, "SuccessConnToDbEle", ".//text[@caption>'Successfully Connected to']", 30000, null, "11f9c4cd-16fa-4342-8d2f-6e7a0a1a854a");
                _yourserverisacceptingsocketconnectiInfo = new RepoItemInfo(this, "YourServerIsAcceptingSocketConnecti", "?/?/container[@type='JPanel']/container[@type='JScrollPane']/container[@name='viewport']/?/?/body/table[1]/tr/td[2]/tag[@innertext>'Your server is accepting socket']", 30000, null, "db770779-1eb8-41b6-828e-2ff9e9ddb50e");
                _successfullyconnectedtodatabaseusingInfo = new RepoItemInfo(this, "SuccessfullyConnectedToDatabaseUsing", "?/?/container[@type='JPanel']/container[@type='JScrollPane']/container[@name='viewport']/?/?/body/table[2]/tr/td[2]/tag[@innertext>'Successfully connected to']", 30000, null, "f7691480-d0d2-40c0-b597-4c5dbd10da32");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("da1c9984-be94-4ea0-a3e1-8db07d76f1f9")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("da1c9984-be94-4ea0-a3e1-8db07d76f1f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SuccessConnToDbEle item.
            /// </summary>
            [RepositoryItem("11f9c4cd-16fa-4342-8d2f-6e7a0a1a854a")]
            public virtual Ranorex.Text SuccessConnToDbEle
            {
                get
                {
                    return _successconntodbeleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SuccessConnToDbEle item info.
            /// </summary>
            [RepositoryItemInfo("11f9c4cd-16fa-4342-8d2f-6e7a0a1a854a")]
            public virtual RepoItemInfo SuccessConnToDbEleInfo
            {
                get
                {
                    return _successconntodbeleInfo;
                }
            }

            /// <summary>
            /// The YourServerIsAcceptingSocketConnecti item.
            /// </summary>
            [RepositoryItem("db770779-1eb8-41b6-828e-2ff9e9ddb50e")]
            public virtual Ranorex.WebElement YourServerIsAcceptingSocketConnecti
            {
                get
                {
                    return _yourserverisacceptingsocketconnectiInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The YourServerIsAcceptingSocketConnecti item info.
            /// </summary>
            [RepositoryItemInfo("db770779-1eb8-41b6-828e-2ff9e9ddb50e")]
            public virtual RepoItemInfo YourServerIsAcceptingSocketConnectiInfo
            {
                get
                {
                    return _yourserverisacceptingsocketconnectiInfo;
                }
            }

            /// <summary>
            /// The SuccessfullyConnectedToDatabaseUsing item.
            /// </summary>
            [RepositoryItem("f7691480-d0d2-40c0-b597-4c5dbd10da32")]
            public virtual Ranorex.WebElement SuccessfullyConnectedToDatabaseUsing
            {
                get
                {
                    return _successfullyconnectedtodatabaseusingInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The SuccessfullyConnectedToDatabaseUsing item info.
            /// </summary>
            [RepositoryItemInfo("f7691480-d0d2-40c0-b597-4c5dbd10da32")]
            public virtual RepoItemInfo SuccessfullyConnectedToDatabaseUsingInfo
            {
                get
                {
                    return _successfullyconnectedtodatabaseusingInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
