///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADS_start
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ADS_startRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("09521d48-2e8b-451f-ba27-57dec2960a58")]
    public partial class ADS_startRepository : RepoGenBaseFolder
    {
        static ADS_startRepository instance = new ADS_startRepository();
        ADS_startRepositoryFolders.LicenseForAquaDataStudioAppFolder _licenseforaquadatastudio;
        ADS_startRepositoryFolders.AquaDataStudioEvaluationAppFolder _aquadatastudioevaluation;
        ADS_startRepositoryFolders.DatastudioAppFolder _datastudio;

        /// <summary>
        /// Gets the singleton class instance representing the ADS_startRepository element repository.
        /// </summary>
        [RepositoryFolder("09521d48-2e8b-451f-ba27-57dec2960a58")]
        public static ADS_startRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ADS_startRepository() 
            : base("ADS_startRepository", "/", null, 0, false, "09521d48-2e8b-451f-ba27-57dec2960a58", ".\\RepositoryImages\\ADS_startRepository09521d48.rximgres")
        {
            _licenseforaquadatastudio = new ADS_startRepositoryFolders.LicenseForAquaDataStudioAppFolder(this);
            _aquadatastudioevaluation = new ADS_startRepositoryFolders.AquaDataStudioEvaluationAppFolder(this);
            _datastudio = new ADS_startRepositoryFolders.DatastudioAppFolder(this);
        }

#region Variables

        string _srTypeEle = "MS SQL Server";

        /// <summary>
        /// Gets or sets the value of variable srTypeEle.
        /// </summary>
        [TestVariable("e36a9491-016d-4170-ab94-6b2333a199fd")]
        public string srTypeEle
        {
            get { return _srTypeEle; }
            set { _srTypeEle = value; }
        }

        string _WindowsAuthTypeRepo = "Windows Authentication";

        /// <summary>
        /// Gets or sets the value of variable WindowsAuthTypeRepo.
        /// </summary>
        [TestVariable("efcc0d3f-cc81-4ccb-8c68-81a82aa4b4e0")]
        public string WindowsAuthTypeRepo
        {
            get { return _WindowsAuthTypeRepo; }
            set { _WindowsAuthTypeRepo = value; }
        }

        string _serverTypeRepo = "";

        /// <summary>
        /// Gets or sets the value of variable serverTypeRepo.
        /// </summary>
        [TestVariable("f06f87fb-c43e-4190-937c-e634c3eba7a4")]
        public string serverTypeRepo
        {
            get { return _serverTypeRepo; }
            set { _serverTypeRepo = value; }
        }

        string _windowTitleRepo = "";

        /// <summary>
        /// Gets or sets the value of variable windowTitleRepo.
        /// </summary>
        [TestVariable("4273f741-de34-4281-9908-4d328ca4a695")]
        public string windowTitleRepo
        {
            get { return _windowTitleRepo; }
            set { _windowTitleRepo = value; }
        }

        string _serverType1Repo = "MS SQL Server";

        /// <summary>
        /// Gets or sets the value of variable serverType1Repo.
        /// </summary>
        [TestVariable("ab081ae0-4e16-4a59-bd53-15e319cec3b0")]
        public string serverType1Repo
        {
            get { return _serverType1Repo; }
            set { _serverType1Repo = value; }
        }

        string _deRegisterServerNameRepo = "SqlServerNew";

        /// <summary>
        /// Gets or sets the value of variable deRegisterServerNameRepo.
        /// </summary>
        [TestVariable("0a2d52e5-febc-470e-a9a9-22f9a8dbd8e6")]
        public string deRegisterServerNameRepo
        {
            get { return _deRegisterServerNameRepo; }
            set { _deRegisterServerNameRepo = value; }
        }

        string _unRegisterServerNameRepo = "";

        /// <summary>
        /// Gets or sets the value of variable unRegisterServerNameRepo.
        /// </summary>
        [TestVariable("a22a1f6e-ab61-47d4-9688-78413c9ec2b1")]
        public string unRegisterServerNameRepo
        {
            get { return _unRegisterServerNameRepo; }
            set { _unRegisterServerNameRepo = value; }
        }

        string _ServerNameRepo = "";

        /// <summary>
        /// Gets or sets the value of variable ServerNameRepo.
        /// </summary>
        [TestVariable("0b4e3dd5-45c3-4284-b60a-4a42c1fbafc3")]
        public string ServerNameRepo
        {
            get { return _ServerNameRepo; }
            set { _ServerNameRepo = value; }
        }

        string _QueryWindowNameRepo = "";

        /// <summary>
        /// Gets or sets the value of variable QueryWindowNameRepo.
        /// </summary>
        [TestVariable("e9469612-a759-408d-a953-1561f7d804ee")]
        public string QueryWindowNameRepo
        {
            get { return _QueryWindowNameRepo; }
            set { _QueryWindowNameRepo = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("09521d48-2e8b-451f-ba27-57dec2960a58")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LicenseForAquaDataStudio folder.
        /// </summary>
        [RepositoryFolder("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
        public virtual ADS_startRepositoryFolders.LicenseForAquaDataStudioAppFolder LicenseForAquaDataStudio
        {
            get { return _licenseforaquadatastudio; }
        }

        /// <summary>
        /// The AquaDataStudioEvaluation folder.
        /// </summary>
        [RepositoryFolder("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
        public virtual ADS_startRepositoryFolders.AquaDataStudioEvaluationAppFolder AquaDataStudioEvaluation
        {
            get { return _aquadatastudioevaluation; }
        }

        /// <summary>
        /// The Datastudio folder.
        /// </summary>
        [RepositoryFolder("cf4fbc79-3679-4fb2-8ac2-094be21b7391")]
        public virtual ADS_startRepositoryFolders.DatastudioAppFolder Datastudio
        {
            get { return _datastudio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ADS_startRepositoryFolders
    {
        /// <summary>
        /// The LicenseForAquaDataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
        public partial class LicenseForAquaDataStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _licenseforaquadatastudioInfo;
            RepoItemInfo _evaluateInfo;
            RepoItemInfo _evaluationiwouldliketorequesta1Info;

            /// <summary>
            /// Creates a new LicenseForAquaDataStudio  folder.
            /// </summary>
            public LicenseForAquaDataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LicenseForAquaDataStudio", "/form[@title>'License for Aqua Data Stu']", parentFolder, 30000, null, false, "10dc2930-1f3b-4ee4-9f04-c97c260319fc", "")
            {
                _licenseforaquadatastudioInfo = new RepoItemInfo(this, "LicenseForAquaDataStudio", "titlebar[@accessiblerole='TitleBar']", 30000, null, "e99ad039-0823-4862-9394-de44ea2dfd00");
                _evaluateInfo = new RepoItemInfo(this, "Evaluate", "container[2]/container[@name='fyG']//button[@name='fyo']", 30000, null, "187f23b6-7f6f-4a3f-9bea-4848000fe6d8");
                _evaluationiwouldliketorequesta1Info = new RepoItemInfo(this, "EvaluationIWouldLikeToRequestA1", "container[1]/?/?/radiobutton[@name='fyI']", 30000, null, "9365f044-54a3-43a8-a79d-31c13afa2d79");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("10dc2930-1f3b-4ee4-9f04-c97c260319fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LicenseForAquaDataStudio item.
            /// </summary>
            [RepositoryItem("e99ad039-0823-4862-9394-de44ea2dfd00")]
            public virtual Ranorex.TitleBar LicenseForAquaDataStudio
            {
                get
                {
                    return _licenseforaquadatastudioInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The LicenseForAquaDataStudio item info.
            /// </summary>
            [RepositoryItemInfo("e99ad039-0823-4862-9394-de44ea2dfd00")]
            public virtual RepoItemInfo LicenseForAquaDataStudioInfo
            {
                get
                {
                    return _licenseforaquadatastudioInfo;
                }
            }

            /// <summary>
            /// The Evaluate item.
            /// </summary>
            [RepositoryItem("187f23b6-7f6f-4a3f-9bea-4848000fe6d8")]
            public virtual Ranorex.Button Evaluate
            {
                get
                {
                    return _evaluateInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Evaluate item info.
            /// </summary>
            [RepositoryItemInfo("187f23b6-7f6f-4a3f-9bea-4848000fe6d8")]
            public virtual RepoItemInfo EvaluateInfo
            {
                get
                {
                    return _evaluateInfo;
                }
            }

            /// <summary>
            /// The EvaluationIWouldLikeToRequestA1 item.
            /// </summary>
            [RepositoryItem("9365f044-54a3-43a8-a79d-31c13afa2d79")]
            public virtual Ranorex.RadioButton EvaluationIWouldLikeToRequestA1
            {
                get
                {
                    return _evaluationiwouldliketorequesta1Info.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The EvaluationIWouldLikeToRequestA1 item info.
            /// </summary>
            [RepositoryItemInfo("9365f044-54a3-43a8-a79d-31c13afa2d79")]
            public virtual RepoItemInfo EvaluationIWouldLikeToRequestA1Info
            {
                get
                {
                    return _evaluationiwouldliketorequesta1Info;
                }
            }
        }

        /// <summary>
        /// The AquaDataStudioEvaluationAppFolder folder.
        /// </summary>
        [RepositoryFolder("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
        public partial class AquaDataStudioEvaluationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aquadatastudioevaluationInfo;
            RepoItemInfo _databaseserverseleInfo;
            RepoItemInfo _sqlservernewInfo;
            DbSchemaNameEleInfoClass _dbschemanameeleInfo;
            RepoItemInfo _testabatsqlservernewuntitled31Info;

            /// <summary>
            /// Creates a new AquaDataStudioEvaluation  folder.
            /// </summary>
            public AquaDataStudioEvaluationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AquaDataStudioEvaluation", "/form[@title>'Aqua Data Studio - [Evalu']", parentFolder, 30000, null, false, "2cce129c-63ba-4d14-8126-6d1c4f35948d", "")
            {
                _aquadatastudioevaluationInfo = new RepoItemInfo(this, "AquaDataStudioEvaluation", "titlebar[@accessiblerole='TitleBar']", 30000, null, "905a42f9-8c43-4f69-bf97-5202952990bf");
                _databaseserverseleInfo = new RepoItemInfo(this, "DatabaseServersEle", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='fLp']/?/?/treeitem[@text='Local Database Servers']", 30000, null, "134da088-e423-4baf-91a3-d7088f21cea7");
                _sqlservernewInfo = new RepoItemInfo(this, "SqlServerNew", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='fLp']//treeitem[@text='SqlServerNew']", 30000, null, "ae0a3676-ec8e-48ce-88f7-4c7000f63f13");
                _dbschemanameeleInfo = new DbSchemaNameEleInfoClass(this);
                _testabatsqlservernewuntitled31Info = new RepoItemInfo(this, "TestabAtSqlServerNewUntitled31", "?/?/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//tabpage[@index='1']", 30000, null, "a3ac2d3f-6ceb-451f-ab96-f2f8e0edaaf9");
            }

            /// <summary>
            /// The DbSchemaNameEleInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("8c59bb66-8db4-4b94-a8b6-f4bbe5b498f7")]
            public class DbSchemaNameEleInfoClass : RepoItemInfo
            {
                /// <summary>
                /// DbSchemaNameEleInfoClass class constructor.
                /// </summary>
                public DbSchemaNameEleInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "DbSchemaNameEle", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']/?/?/container[@accessiblename='testab@SqlServerNew [Untitled 3]']/container[3]//container[@name='gEv']//combobox[@name='dZ']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "8c59bb66-8db4-4b94-a8b6-f4bbe5b498f7")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("144f7111-9b68-4115-ba9f-939ca8688b1d")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("144f7111-9b68-4115-ba9f-939ca8688b1d");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("144f7111-9b68-4115-ba9f-939ca8688b1d")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("144f7111-9b68-4115-ba9f-939ca8688b1d", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2cce129c-63ba-4d14-8126-6d1c4f35948d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AquaDataStudioEvaluation item.
            /// </summary>
            [RepositoryItem("905a42f9-8c43-4f69-bf97-5202952990bf")]
            public virtual Ranorex.TitleBar AquaDataStudioEvaluation
            {
                get
                {
                    return _aquadatastudioevaluationInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The AquaDataStudioEvaluation item info.
            /// </summary>
            [RepositoryItemInfo("905a42f9-8c43-4f69-bf97-5202952990bf")]
            public virtual RepoItemInfo AquaDataStudioEvaluationInfo
            {
                get
                {
                    return _aquadatastudioevaluationInfo;
                }
            }

            /// <summary>
            /// The DatabaseServersEle item.
            /// </summary>
            [RepositoryItem("134da088-e423-4baf-91a3-d7088f21cea7")]
            public virtual Ranorex.TreeItem DatabaseServersEle
            {
                get
                {
                    return _databaseserverseleInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DatabaseServersEle item info.
            /// </summary>
            [RepositoryItemInfo("134da088-e423-4baf-91a3-d7088f21cea7")]
            public virtual RepoItemInfo DatabaseServersEleInfo
            {
                get
                {
                    return _databaseserverseleInfo;
                }
            }

            /// <summary>
            /// The SqlServerNew item.
            /// </summary>
            [RepositoryItem("ae0a3676-ec8e-48ce-88f7-4c7000f63f13")]
            public virtual Ranorex.TreeItem SqlServerNew
            {
                get
                {
                    return _sqlservernewInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SqlServerNew item info.
            /// </summary>
            [RepositoryItemInfo("ae0a3676-ec8e-48ce-88f7-4c7000f63f13")]
            public virtual RepoItemInfo SqlServerNewInfo
            {
                get
                {
                    return _sqlservernewInfo;
                }
            }

            /// <summary>
            /// The DbSchemaNameEle item.
            /// </summary>
            [RepositoryItem("8c59bb66-8db4-4b94-a8b6-f4bbe5b498f7")]
            public virtual Ranorex.Text DbSchemaNameEle
            {
                get
                {
                    return _dbschemanameeleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DbSchemaNameEle item info.
            /// </summary>
            [RepositoryItemInfo("8c59bb66-8db4-4b94-a8b6-f4bbe5b498f7")]
            public virtual DbSchemaNameEleInfoClass DbSchemaNameEleInfo
            {
                get
                {
                    return _dbschemanameeleInfo;
                }
            }

            /// <summary>
            /// The TestabAtSqlServerNewUntitled31 item.
            /// </summary>
            [RepositoryItem("a3ac2d3f-6ceb-451f-ab96-f2f8e0edaaf9")]
            public virtual Ranorex.TabPage TestabAtSqlServerNewUntitled31
            {
                get
                {
                    return _testabatsqlservernewuntitled31Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestabAtSqlServerNewUntitled31 item info.
            /// </summary>
            [RepositoryItemInfo("a3ac2d3f-6ceb-451f-ab96-f2f8e0edaaf9")]
            public virtual RepoItemInfo TestabAtSqlServerNewUntitled31Info
            {
                get
                {
                    return _testabatsqlservernewuntitled31Info;
                }
            }
        }

        /// <summary>
        /// The DatastudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("cf4fbc79-3679-4fb2-8ac2-094be21b7391")]
        public partial class DatastudioAppFolder : RepoGenBaseFolder
        {
            ADS_startRepositoryFolders.ContainerFYsFolder _containerfys;
            ADS_startRepositoryFolders.ComboBoxListFolder _comboboxlist;
            ADS_startRepositoryFolders.JPanelFolder _jpanel;
            RepoItemInfo _registerservereleInfo;
            RepoItemInfo _regrservertitlebarformeleInfo;
            RepoItemInfo _testconnbtneleInfo;
            RepoItemInfo _saveserverregeleInfo;
            RepoItemInfo _closetestconneleInfo;
            RepoItemInfo _servertypeeleInfo;
            RepoItemInfo _servermaineleInfo;
            RepoItemInfo _unregisterservereleInfo;
            RepoItemInfo _unregisterpopupbuttonyeseleInfo;
            RepoItemInfo _sqlservernewInfo;
            RepoItemInfo _serverpropertieseleInfo;
            RepoItemInfo _scriptmenueleInfo;
            RepoItemInfo _scriptediteleInfo;
            RepoItemInfo _saveserverpropeleInfo;
            RepoItemInfo _schemachangepopupeleInfo;
            RepoItemInfo _queryanalyzereleInfo;
            RepoItemInfo _queryanalyzerwindowtitleeleInfo;
            RepoItemInfo _servermenueleInfo;

            /// <summary>
            /// Creates a new Datastudio  folder.
            /// </summary>
            public DatastudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio", "/form[@processname='datastudio']", parentFolder, 30000, null, false, "cf4fbc79-3679-4fb2-8ac2-094be21b7391", "")
            {
                _containerfys = new ADS_startRepositoryFolders.ContainerFYsFolder(this);
                _comboboxlist = new ADS_startRepositoryFolders.ComboBoxListFolder(this);
                _jpanel = new ADS_startRepositoryFolders.JPanelFolder(this);
                _registerservereleInfo = new RepoItemInfo(this, "RegisterServerEle", "?/?/menuitem[@text='Register Server']", 30000, null, "901d7c4b-ac71-4a8b-9fd8-ee893a8af108");
                _regrservertitlebarformeleInfo = new RepoItemInfo(this, "RegrServerTitleBarFormEle", "titlebar[@accessiblerole='TitleBar']", 30000, null, "f51fcf82-8b96-4702-be12-733d436a525c");
                _testconnbtneleInfo = new RepoItemInfo(this, "TestConnBtnEle", "container[@type='Iꅟꎴꏁͦ7for']/?/?/button[@name='fYo']", 30000, null, "25849581-d360-4865-8b2e-5b0895c86adf");
                _saveserverregeleInfo = new RepoItemInfo(this, "SaveServerRegEle", "container[@type='Iꅟꎴꏁͦ7for']/?/?/button[@name='fxO']", 30000, null, "c8eb4347-55f9-499f-a71b-2a42c1d41100");
                _closetestconneleInfo = new RepoItemInfo(this, "CloseTestConnEle", "container[@type='JPanel']/container[@type='Iꅟꎴꏁͦ7for']//button[@name='defaultButton']", 30000, null, "bec9ae60-cd28-4dbf-b05b-e71a4ff48d21");
                _servertypeeleInfo = new RepoItemInfo(this, "serverTypeEle", "?/?/container[@name='fXv']/?/?/container[@name='fXG']/?/?/list[@name='fXF']/listitem[@text=$serverTypeRepo]", 30000, null, "8acce1c8-3d71-409c-bf2e-d410e1f241df");
                _servermaineleInfo = new RepoItemInfo(this, "ServerMainEle", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='fLp']//treeitem[@text=$ServerNameRepo]", 30000, null, "7f63d772-36b5-4e51-8c34-33f5f2637512");
                _unregisterservereleInfo = new RepoItemInfo(this, "UnregisterServerEle", "?/?/menuitem[@text='Unregister Server']", 30000, null, "84f47009-bfac-4da9-8534-9469317e17a6");
                _unregisterpopupbuttonyeseleInfo = new RepoItemInfo(this, "UnRegisterPopupButtonYesEle", "?/?/container[@name='OptionPane.buttonArea']/button[@text='Yes']", 30000, null, "75edcada-6cd7-449c-9ac3-18cf63c72948");
                _sqlservernewInfo = new RepoItemInfo(this, "SqlServerNew", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='fLp']//treeitem[@text='SqlServerNew']", 30000, null, "626f2d9a-9bc8-43e5-8759-272e17769f0d");
                _serverpropertieseleInfo = new RepoItemInfo(this, "ServerPropertiesEle", "?/?/menuitem[@text='Server Properties']", 30000, null, "0ceb77a7-c568-470b-85b8-52d48a3f1660");
                _scriptmenueleInfo = new RepoItemInfo(this, "ScriptMenuEle", "?/?/tabpage[@title='Script   ']", 30000, null, "3ec45860-3fad-4e88-958e-032bce7361d7");
                _scriptediteleInfo = new RepoItemInfo(this, "scriptEditEle", "container[@name='fSs']/container[@name='fYl']//container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "29a1cb0c-2012-4775-a596-6b1d9d85515a");
                _saveserverpropeleInfo = new RepoItemInfo(this, "SaveServerPropEle", "container[@type='Iꅟꎴꏁͦ7for']/?/?/button[@name='defaultButton']", 30000, null, "29fd9fb8-e83c-42d8-818d-00d961799815");
                _schemachangepopupeleInfo = new RepoItemInfo(this, "SchemaChangePopupEle", ".//container[@name='OptionPane.realBody']/container[@name='OptionPane.body']/text[@name='OptionPane.label']", 30000, null, "bd1f7815-f054-44d2-bcd8-8b2d62b47f84");
                _queryanalyzereleInfo = new RepoItemInfo(this, "QueryAnalyzerEle", "?/?/menuitem[@text='Query Analyzer']", 30000, null, "363577a4-cf47-434c-abb8-ede23baceac1");
                _queryanalyzerwindowtitleeleInfo = new RepoItemInfo(this, "QueryAnalyzerWindowTitleEle", "?/?/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//tabpage[@title>$QueryWindowNameRepo]", 30000, null, "ade73a48-3c8d-4d49-85a3-f37009fdea3f");
                _servermenueleInfo = new RepoItemInfo(this, "ServerMenuEle", "?/?/menuitem[@text='Server']", 30000, null, "34473eff-4bfb-4aac-9348-b91e76924012");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf4fbc79-3679-4fb2-8ac2-094be21b7391")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf4fbc79-3679-4fb2-8ac2-094be21b7391")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RegisterServerEle item.
            /// </summary>
            [RepositoryItem("901d7c4b-ac71-4a8b-9fd8-ee893a8af108")]
            public virtual Ranorex.MenuItem RegisterServerEle
            {
                get
                {
                    return _registerservereleInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The RegisterServerEle item info.
            /// </summary>
            [RepositoryItemInfo("901d7c4b-ac71-4a8b-9fd8-ee893a8af108")]
            public virtual RepoItemInfo RegisterServerEleInfo
            {
                get
                {
                    return _registerservereleInfo;
                }
            }

            /// <summary>
            /// The RegrServerTitleBarFormEle item.
            /// </summary>
            [RepositoryItem("f51fcf82-8b96-4702-be12-733d436a525c")]
            public virtual Ranorex.TitleBar RegrServerTitleBarFormEle
            {
                get
                {
                    return _regrservertitlebarformeleInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The RegrServerTitleBarFormEle item info.
            /// </summary>
            [RepositoryItemInfo("f51fcf82-8b96-4702-be12-733d436a525c")]
            public virtual RepoItemInfo RegrServerTitleBarFormEleInfo
            {
                get
                {
                    return _regrservertitlebarformeleInfo;
                }
            }

            /// <summary>
            /// The TestConnBtnEle item.
            /// </summary>
            [RepositoryItem("25849581-d360-4865-8b2e-5b0895c86adf")]
            public virtual Ranorex.Button TestConnBtnEle
            {
                get
                {
                    return _testconnbtneleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TestConnBtnEle item info.
            /// </summary>
            [RepositoryItemInfo("25849581-d360-4865-8b2e-5b0895c86adf")]
            public virtual RepoItemInfo TestConnBtnEleInfo
            {
                get
                {
                    return _testconnbtneleInfo;
                }
            }

            /// <summary>
            /// The SaveServerRegEle item.
            /// </summary>
            [RepositoryItem("c8eb4347-55f9-499f-a71b-2a42c1d41100")]
            public virtual Ranorex.Button SaveServerRegEle
            {
                get
                {
                    return _saveserverregeleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveServerRegEle item info.
            /// </summary>
            [RepositoryItemInfo("c8eb4347-55f9-499f-a71b-2a42c1d41100")]
            public virtual RepoItemInfo SaveServerRegEleInfo
            {
                get
                {
                    return _saveserverregeleInfo;
                }
            }

            /// <summary>
            /// The CloseTestConnEle item.
            /// </summary>
            [RepositoryItem("bec9ae60-cd28-4dbf-b05b-e71a4ff48d21")]
            public virtual Ranorex.Button CloseTestConnEle
            {
                get
                {
                    return _closetestconneleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseTestConnEle item info.
            /// </summary>
            [RepositoryItemInfo("bec9ae60-cd28-4dbf-b05b-e71a4ff48d21")]
            public virtual RepoItemInfo CloseTestConnEleInfo
            {
                get
                {
                    return _closetestconneleInfo;
                }
            }

            /// <summary>
            /// The serverTypeEle item.
            /// </summary>
            [RepositoryItem("8acce1c8-3d71-409c-bf2e-d410e1f241df")]
            public virtual Ranorex.ListItem serverTypeEle
            {
                get
                {
                    return _servertypeeleInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The serverTypeEle item info.
            /// </summary>
            [RepositoryItemInfo("8acce1c8-3d71-409c-bf2e-d410e1f241df")]
            public virtual RepoItemInfo serverTypeEleInfo
            {
                get
                {
                    return _servertypeeleInfo;
                }
            }

            /// <summary>
            /// The ServerMainEle item.
            /// </summary>
            [RepositoryItem("7f63d772-36b5-4e51-8c34-33f5f2637512")]
            public virtual Ranorex.TreeItem ServerMainEle
            {
                get
                {
                    return _servermaineleInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The ServerMainEle item info.
            /// </summary>
            [RepositoryItemInfo("7f63d772-36b5-4e51-8c34-33f5f2637512")]
            public virtual RepoItemInfo ServerMainEleInfo
            {
                get
                {
                    return _servermaineleInfo;
                }
            }

            /// <summary>
            /// The UnregisterServerEle item.
            /// </summary>
            [RepositoryItem("84f47009-bfac-4da9-8534-9469317e17a6")]
            public virtual Ranorex.MenuItem UnregisterServerEle
            {
                get
                {
                    return _unregisterservereleInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The UnregisterServerEle item info.
            /// </summary>
            [RepositoryItemInfo("84f47009-bfac-4da9-8534-9469317e17a6")]
            public virtual RepoItemInfo UnregisterServerEleInfo
            {
                get
                {
                    return _unregisterservereleInfo;
                }
            }

            /// <summary>
            /// The UnRegisterPopupButtonYesEle item.
            /// </summary>
            [RepositoryItem("75edcada-6cd7-449c-9ac3-18cf63c72948")]
            public virtual Ranorex.Button UnRegisterPopupButtonYesEle
            {
                get
                {
                    return _unregisterpopupbuttonyeseleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UnRegisterPopupButtonYesEle item info.
            /// </summary>
            [RepositoryItemInfo("75edcada-6cd7-449c-9ac3-18cf63c72948")]
            public virtual RepoItemInfo UnRegisterPopupButtonYesEleInfo
            {
                get
                {
                    return _unregisterpopupbuttonyeseleInfo;
                }
            }

            /// <summary>
            /// The SqlServerNew item.
            /// </summary>
            [RepositoryItem("626f2d9a-9bc8-43e5-8759-272e17769f0d")]
            public virtual Ranorex.TreeItem SqlServerNew
            {
                get
                {
                    return _sqlservernewInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SqlServerNew item info.
            /// </summary>
            [RepositoryItemInfo("626f2d9a-9bc8-43e5-8759-272e17769f0d")]
            public virtual RepoItemInfo SqlServerNewInfo
            {
                get
                {
                    return _sqlservernewInfo;
                }
            }

            /// <summary>
            /// The ServerPropertiesEle item.
            /// </summary>
            [RepositoryItem("0ceb77a7-c568-470b-85b8-52d48a3f1660")]
            public virtual Ranorex.MenuItem ServerPropertiesEle
            {
                get
                {
                    return _serverpropertieseleInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ServerPropertiesEle item info.
            /// </summary>
            [RepositoryItemInfo("0ceb77a7-c568-470b-85b8-52d48a3f1660")]
            public virtual RepoItemInfo ServerPropertiesEleInfo
            {
                get
                {
                    return _serverpropertieseleInfo;
                }
            }

            /// <summary>
            /// The ScriptMenuEle item.
            /// </summary>
            [RepositoryItem("3ec45860-3fad-4e88-958e-032bce7361d7")]
            public virtual Ranorex.TabPage ScriptMenuEle
            {
                get
                {
                    return _scriptmenueleInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ScriptMenuEle item info.
            /// </summary>
            [RepositoryItemInfo("3ec45860-3fad-4e88-958e-032bce7361d7")]
            public virtual RepoItemInfo ScriptMenuEleInfo
            {
                get
                {
                    return _scriptmenueleInfo;
                }
            }

            /// <summary>
            /// The scriptEditEle item.
            /// </summary>
            [RepositoryItem("29a1cb0c-2012-4775-a596-6b1d9d85515a")]
            public virtual Ranorex.Unknown scriptEditEle
            {
                get
                {
                    return _scriptediteleInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The scriptEditEle item info.
            /// </summary>
            [RepositoryItemInfo("29a1cb0c-2012-4775-a596-6b1d9d85515a")]
            public virtual RepoItemInfo scriptEditEleInfo
            {
                get
                {
                    return _scriptediteleInfo;
                }
            }

            /// <summary>
            /// The SaveServerPropEle item.
            /// </summary>
            [RepositoryItem("29fd9fb8-e83c-42d8-818d-00d961799815")]
            public virtual Ranorex.Button SaveServerPropEle
            {
                get
                {
                    return _saveserverpropeleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveServerPropEle item info.
            /// </summary>
            [RepositoryItemInfo("29fd9fb8-e83c-42d8-818d-00d961799815")]
            public virtual RepoItemInfo SaveServerPropEleInfo
            {
                get
                {
                    return _saveserverpropeleInfo;
                }
            }

            /// <summary>
            /// The SchemaChangePopupEle item.
            /// </summary>
            [RepositoryItem("bd1f7815-f054-44d2-bcd8-8b2d62b47f84")]
            public virtual Ranorex.Text SchemaChangePopupEle
            {
                get
                {
                    return _schemachangepopupeleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SchemaChangePopupEle item info.
            /// </summary>
            [RepositoryItemInfo("bd1f7815-f054-44d2-bcd8-8b2d62b47f84")]
            public virtual RepoItemInfo SchemaChangePopupEleInfo
            {
                get
                {
                    return _schemachangepopupeleInfo;
                }
            }

            /// <summary>
            /// The QueryAnalyzerEle item.
            /// </summary>
            [RepositoryItem("363577a4-cf47-434c-abb8-ede23baceac1")]
            public virtual Ranorex.MenuItem QueryAnalyzerEle
            {
                get
                {
                    return _queryanalyzereleInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The QueryAnalyzerEle item info.
            /// </summary>
            [RepositoryItemInfo("363577a4-cf47-434c-abb8-ede23baceac1")]
            public virtual RepoItemInfo QueryAnalyzerEleInfo
            {
                get
                {
                    return _queryanalyzereleInfo;
                }
            }

            /// <summary>
            /// The QueryAnalyzerWindowTitleEle item.
            /// </summary>
            [RepositoryItem("ade73a48-3c8d-4d49-85a3-f37009fdea3f")]
            public virtual Ranorex.TabPage QueryAnalyzerWindowTitleEle
            {
                get
                {
                    return _queryanalyzerwindowtitleeleInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The QueryAnalyzerWindowTitleEle item info.
            /// </summary>
            [RepositoryItemInfo("ade73a48-3c8d-4d49-85a3-f37009fdea3f")]
            public virtual RepoItemInfo QueryAnalyzerWindowTitleEleInfo
            {
                get
                {
                    return _queryanalyzerwindowtitleeleInfo;
                }
            }

            /// <summary>
            /// The ServerMenuEle item.
            /// </summary>
            [RepositoryItem("34473eff-4bfb-4aac-9348-b91e76924012")]
            public virtual Ranorex.MenuItem ServerMenuEle
            {
                get
                {
                    return _servermenueleInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ServerMenuEle item info.
            /// </summary>
            [RepositoryItemInfo("34473eff-4bfb-4aac-9348-b91e76924012")]
            public virtual RepoItemInfo ServerMenuEleInfo
            {
                get
                {
                    return _servermenueleInfo;
                }
            }

            /// <summary>
            /// The ContainerFYs folder.
            /// </summary>
            [RepositoryFolder("5ce8ad34-b2a1-4077-bd81-84cf5b154ccf")]
            public virtual ADS_startRepositoryFolders.ContainerFYsFolder ContainerFYs
            {
                get { return _containerfys; }
            }

            /// <summary>
            /// The ComboBoxList folder.
            /// </summary>
            [RepositoryFolder("341885ab-20f8-43d1-aa7c-9792e2c05866")]
            public virtual ADS_startRepositoryFolders.ComboBoxListFolder ComboBoxList
            {
                get { return _comboboxlist; }
            }

            /// <summary>
            /// The JPanel folder.
            /// </summary>
            [RepositoryFolder("da1c9984-be94-4ea0-a3e1-8db07d76f1f9")]
            public virtual ADS_startRepositoryFolders.JPanelFolder JPanel
            {
                get { return _jpanel; }
            }
        }

        /// <summary>
        /// The ContainerFYsFolder folder.
        /// </summary>
        [RepositoryFolder("5ce8ad34-b2a1-4077-bd81-84cf5b154ccf")]
        public partial class ContainerFYsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _comboauthtypeeleInfo;
            RepoItemInfo _loginpwdeleInfo;
            RepoItemInfo _logintxteleInfo;
            RepoItemInfo _combodrivereleInfo;
            RepoItemInfo _hostnameeleInfo;
            RepoItemInfo _nameservereleInfo;

            /// <summary>
            /// Creates a new ContainerFYs  folder.
            /// </summary>
            public ContainerFYsFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerFYs", "container[@name='fSs']/container[@name='fXv']/?/?/container[@name='fYs']", parentFolder, 30000, null, false, "5ce8ad34-b2a1-4077-bd81-84cf5b154ccf", "")
            {
                _comboauthtypeeleInfo = new RepoItemInfo(this, "ComboAuthTypeEle", ".//container[@type='Pꈘᜬᛌᝊtransient5']/?/?/combobox[@name='eXC']", 30000, null, "c3cec3c5-dc17-4c1d-b8af-a5582580e068");
                _loginpwdeleInfo = new RepoItemInfo(this, "LoginPwdEle", ".//container[@type='Pꈘᜬᛌᝊtransient5']/?/?/text[@type='JPasswordField']", 30000, null, "4f9346da-db00-451c-ae3b-49ea11626fc4");
                _logintxteleInfo = new RepoItemInfo(this, "LoginTxtEle", ".//container[@type='Pꈘᜬᛌᝊtransient5']/?/?/text[@type='JTextField']", 30000, null, "0e4df0ae-1d62-4eca-86db-5aec59a7857f");
                _combodrivereleInfo = new RepoItemInfo(this, "comboDriverEle", ".//container[@name='gfP']/?/?/combobox[@name='gfH']", 30000, null, "63f55ca4-4abc-46c4-96f5-35c52925373a");
                _hostnameeleInfo = new RepoItemInfo(this, "hostNameEle", ".//container[@name='gfT']/text[@name='_actualComponent']", 30000, null, "babc60d0-c366-4a1d-93ce-0f01c99858bf");
                _nameservereleInfo = new RepoItemInfo(this, "NameServerEle", ".//container[@name='fYq']/?/?/text[@name='ec']", 30000, null, "39ab3480-210a-42ed-8a7c-7285b2571707");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5ce8ad34-b2a1-4077-bd81-84cf5b154ccf")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5ce8ad34-b2a1-4077-bd81-84cf5b154ccf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ComboAuthTypeEle item.
            /// </summary>
            [RepositoryItem("c3cec3c5-dc17-4c1d-b8af-a5582580e068")]
            public virtual Ranorex.ComboBox ComboAuthTypeEle
            {
                get
                {
                    return _comboauthtypeeleInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboAuthTypeEle item info.
            /// </summary>
            [RepositoryItemInfo("c3cec3c5-dc17-4c1d-b8af-a5582580e068")]
            public virtual RepoItemInfo ComboAuthTypeEleInfo
            {
                get
                {
                    return _comboauthtypeeleInfo;
                }
            }

            /// <summary>
            /// The LoginPwdEle item.
            /// </summary>
            [RepositoryItem("4f9346da-db00-451c-ae3b-49ea11626fc4")]
            public virtual Ranorex.Text LoginPwdEle
            {
                get
                {
                    return _loginpwdeleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LoginPwdEle item info.
            /// </summary>
            [RepositoryItemInfo("4f9346da-db00-451c-ae3b-49ea11626fc4")]
            public virtual RepoItemInfo LoginPwdEleInfo
            {
                get
                {
                    return _loginpwdeleInfo;
                }
            }

            /// <summary>
            /// The LoginTxtEle item.
            /// </summary>
            [RepositoryItem("0e4df0ae-1d62-4eca-86db-5aec59a7857f")]
            public virtual Ranorex.Text LoginTxtEle
            {
                get
                {
                    return _logintxteleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LoginTxtEle item info.
            /// </summary>
            [RepositoryItemInfo("0e4df0ae-1d62-4eca-86db-5aec59a7857f")]
            public virtual RepoItemInfo LoginTxtEleInfo
            {
                get
                {
                    return _logintxteleInfo;
                }
            }

            /// <summary>
            /// The comboDriverEle item.
            /// </summary>
            [RepositoryItem("63f55ca4-4abc-46c4-96f5-35c52925373a")]
            public virtual Ranorex.ComboBox comboDriverEle
            {
                get
                {
                    return _combodrivereleInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The comboDriverEle item info.
            /// </summary>
            [RepositoryItemInfo("63f55ca4-4abc-46c4-96f5-35c52925373a")]
            public virtual RepoItemInfo comboDriverEleInfo
            {
                get
                {
                    return _combodrivereleInfo;
                }
            }

            /// <summary>
            /// The hostNameEle item.
            /// </summary>
            [RepositoryItem("babc60d0-c366-4a1d-93ce-0f01c99858bf")]
            public virtual Ranorex.Text hostNameEle
            {
                get
                {
                    return _hostnameeleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The hostNameEle item info.
            /// </summary>
            [RepositoryItemInfo("babc60d0-c366-4a1d-93ce-0f01c99858bf")]
            public virtual RepoItemInfo hostNameEleInfo
            {
                get
                {
                    return _hostnameeleInfo;
                }
            }

            /// <summary>
            /// The NameServerEle item.
            /// </summary>
            [RepositoryItem("39ab3480-210a-42ed-8a7c-7285b2571707")]
            public virtual Ranorex.Text NameServerEle
            {
                get
                {
                    return _nameservereleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NameServerEle item info.
            /// </summary>
            [RepositoryItemInfo("39ab3480-210a-42ed-8a7c-7285b2571707")]
            public virtual RepoItemInfo NameServerEleInfo
            {
                get
                {
                    return _nameservereleInfo;
                }
            }
        }

        /// <summary>
        /// The ComboBoxListFolder folder.
        /// </summary>
        [RepositoryFolder("341885ab-20f8-43d1-aa7c-9792e2c05866")]
        public partial class ComboBoxListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _jtdsdrivereleInfo;
            RepoItemInfo _authtypeeleInfo;

            /// <summary>
            /// Creates a new ComboBoxList  folder.
            /// </summary>
            public ComboBoxListFolder(RepoGenBaseFolder parentFolder) :
                    base("ComboBoxList", ".//container[@name='viewport']/list[@name='ComboBox.list']", parentFolder, 30000, null, false, "341885ab-20f8-43d1-aa7c-9792e2c05866", "")
            {
                _jtdsdrivereleInfo = new RepoItemInfo(this, "JTDSDriverEle", "listitem[@text='jTDS']", 30000, null, "d13b784d-77e1-4524-b36a-c092a9174f31");
                _authtypeeleInfo = new RepoItemInfo(this, "AuthTypeEle", "listitem[@text=$WindowsAuthTypeRepo]", 30000, null, "1a4048a2-a48f-41c4-b9c8-943fe2d2e450");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("341885ab-20f8-43d1-aa7c-9792e2c05866")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("341885ab-20f8-43d1-aa7c-9792e2c05866")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JTDSDriverEle item.
            /// </summary>
            [RepositoryItem("d13b784d-77e1-4524-b36a-c092a9174f31")]
            public virtual Ranorex.ListItem JTDSDriverEle
            {
                get
                {
                    return _jtdsdrivereleInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The JTDSDriverEle item info.
            /// </summary>
            [RepositoryItemInfo("d13b784d-77e1-4524-b36a-c092a9174f31")]
            public virtual RepoItemInfo JTDSDriverEleInfo
            {
                get
                {
                    return _jtdsdrivereleInfo;
                }
            }

            /// <summary>
            /// The AuthTypeEle item.
            /// </summary>
            [RepositoryItem("1a4048a2-a48f-41c4-b9c8-943fe2d2e450")]
            public virtual Ranorex.ListItem AuthTypeEle
            {
                get
                {
                    return _authtypeeleInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The AuthTypeEle item info.
            /// </summary>
            [RepositoryItemInfo("1a4048a2-a48f-41c4-b9c8-943fe2d2e450")]
            public virtual RepoItemInfo AuthTypeEleInfo
            {
                get
                {
                    return _authtypeeleInfo;
                }
            }
        }

        /// <summary>
        /// The JPanelFolder folder.
        /// </summary>
        [RepositoryFolder("da1c9984-be94-4ea0-a3e1-8db07d76f1f9")]
        public partial class JPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _successconntodbeleInfo;

            /// <summary>
            /// Creates a new JPanel  folder.
            /// </summary>
            public JPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("JPanel", "container[@type='JPanel']", parentFolder, 30000, null, false, "da1c9984-be94-4ea0-a3e1-8db07d76f1f9", "")
            {
                _successconntodbeleInfo = new RepoItemInfo(this, "SuccessConnToDbEle", ".//text[@caption>'Successfully Connected to']", 30000, null, "11f9c4cd-16fa-4342-8d2f-6e7a0a1a854a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("da1c9984-be94-4ea0-a3e1-8db07d76f1f9")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("da1c9984-be94-4ea0-a3e1-8db07d76f1f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SuccessConnToDbEle item.
            /// </summary>
            [RepositoryItem("11f9c4cd-16fa-4342-8d2f-6e7a0a1a854a")]
            public virtual Ranorex.Text SuccessConnToDbEle
            {
                get
                {
                    return _successconntodbeleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SuccessConnToDbEle item info.
            /// </summary>
            [RepositoryItemInfo("11f9c4cd-16fa-4342-8d2f-6e7a0a1a854a")]
            public virtual RepoItemInfo SuccessConnToDbEleInfo
            {
                get
                {
                    return _successconntodbeleInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
