///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ADS_start
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("046416c2-680f-453d-90c2-bae71ba68164", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ADS_startRepository repository.
        /// </summary>
        public static ADS_startRepository repo = ADS_startRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFYs.LoginTxtEle' at 95;18.", repo.Datastudio.ContainerFYs.LoginTxtEleInfo, new RecordItemIndex(0));
            repo.Datastudio.ContainerFYs.LoginTxtEle.Click("95;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}' with focus on 'Datastudio.ContainerFYs.LoginTxtEle'.", repo.Datastudio.ContainerFYs.LoginTxtEleInfo, new RecordItemIndex(1));
            repo.Datastudio.ContainerFYs.LoginTxtEle.PressKeys("{Back}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'testab' with focus on 'Datastudio.ContainerFYs.LoginTxtEle'.", repo.Datastudio.ContainerFYs.LoginTxtEleInfo, new RecordItemIndex(2));
            repo.Datastudio.ContainerFYs.LoginTxtEle.PressKeys("testab");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFYs.LoginPwdEle' at 100;5.", repo.Datastudio.ContainerFYs.LoginPwdEleInfo, new RecordItemIndex(3));
            repo.Datastudio.ContainerFYs.LoginPwdEle.Click("100;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Datastudio.ContainerFYs.LoginPwdEle' at 100;5.", repo.Datastudio.ContainerFYs.LoginPwdEleInfo, new RecordItemIndex(4));
            repo.Datastudio.ContainerFYs.LoginPwdEle.MoveTo("100;5");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Datastudio.ContainerFYs.LoginPwdEle' at 108;-3.", repo.Datastudio.ContainerFYs.LoginPwdEleInfo, new RecordItemIndex(5));
            repo.Datastudio.ContainerFYs.LoginPwdEle.MoveTo("108;-3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Datastudio.ContainerFYs.Password' at 35;9.", repo.Datastudio.ContainerFYs.PasswordInfo, new RecordItemIndex(6));
            repo.Datastudio.ContainerFYs.Password.MoveTo("35;9");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'synerzip1' with focus on 'Datastudio.ContainerFYs.LoginPwdEle'.", repo.Datastudio.ContainerFYs.LoginPwdEleInfo, new RecordItemIndex(7));
            repo.Datastudio.ContainerFYs.LoginPwdEle.PressKeys("synerzip1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFYs.hostNameEle1' at 44;10.", repo.Datastudio.ContainerFYs.hostNameEle1Info, new RecordItemIndex(8));
            repo.Datastudio.ContainerFYs.hostNameEle1.Click("44;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFSs' at 667;651.", repo.Datastudio.ContainerFSsInfo, new RecordItemIndex(9));
            repo.Datastudio.ContainerFSs.Click("667;651");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFXv' at 524;611.", repo.Datastudio.ContainerFXvInfo, new RecordItemIndex(10));
            repo.Datastudio.ContainerFXv.Click("524;611");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Datastudio.ContainerFYs.JTextField2' at 297;16.", repo.Datastudio.ContainerFYs.JTextField2Info, new RecordItemIndex(11));
            repo.Datastudio.ContainerFYs.JTextField2.MoveTo("297;16");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Datastudio.ContainerFYs.JTextField2' at 136;8.", repo.Datastudio.ContainerFYs.JTextField2Info, new RecordItemIndex(12));
            repo.Datastudio.ContainerFYs.JTextField2.MoveTo("136;8");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+C' Press.", new RecordItemIndex(13));
            Keyboard.Press(System.Windows.Forms.Keys.C | System.Windows.Forms.Keys.Control, 46, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFYs.hostNameEle1' at 42;1.", repo.Datastudio.ContainerFYs.hostNameEle1Info, new RecordItemIndex(14));
            repo.Datastudio.ContainerFYs.hostNameEle1.Click("42;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFYs.hostNameEle1' at 48;7.", repo.Datastudio.ContainerFYs.hostNameEle1Info, new RecordItemIndex(15));
            repo.Datastudio.ContainerFYs.hostNameEle1.Click("48;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+V' Press with focus on 'Datastudio'.", repo.Datastudio.SelfInfo, new RecordItemIndex(16));
            Keyboard.PrepareFocus(repo.Datastudio.Self);
            Keyboard.Press(System.Windows.Forms.Keys.V | System.Windows.Forms.Keys.Control, 47, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Datastudio.RegisterServerTitleBarFormEle' at 732;18.", repo.Datastudio.RegisterServerTitleBarFormEleInfo, new RecordItemIndex(17));
            repo.Datastudio.RegisterServerTitleBarFormEle.MoveTo("732;18");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Datastudio.RegisterServerTitleBarFormEle' at 531;34.", repo.Datastudio.RegisterServerTitleBarFormEleInfo, new RecordItemIndex(18));
            repo.Datastudio.RegisterServerTitleBarFormEle.MoveTo("531;34");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.TestConnBtnEle' at 29;9.", repo.Datastudio.TestConnBtnEleInfo, new RecordItemIndex(19));
            repo.Datastudio.TestConnBtnEle.Click("29;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.JPanel.SuccessfullyConnectedToDatabaseUsing' at 185;0.", repo.Datastudio.JPanel.SuccessfullyConnectedToDatabaseUsingInfo, new RecordItemIndex(20));
            repo.Datastudio.JPanel.SuccessfullyConnectedToDatabaseUsing.Click("185;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.JPanel.YourServerIsAcceptingSocketConnecti' at 187;11.", repo.Datastudio.JPanel.YourServerIsAcceptingSocketConnectiInfo, new RecordItemIndex(21));
            repo.Datastudio.JPanel.YourServerIsAcceptingSocketConnecti.Click("187;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.JPanel.SuccessConnToDbEle' at 203;18.", repo.Datastudio.JPanel.SuccessConnToDbEleInfo, new RecordItemIndex(22));
            repo.Datastudio.JPanel.SuccessConnToDbEle.Click("203;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.RegisterServerTitleBarFormEle' at 200;15.", repo.Datastudio.RegisterServerTitleBarFormEleInfo, new RecordItemIndex(23));
            repo.Datastudio.RegisterServerTitleBarFormEle.Click("200;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.CloseTestConnEle' at 36;13.", repo.Datastudio.CloseTestConnEleInfo, new RecordItemIndex(24));
            repo.Datastudio.CloseTestConnEle.Click("36;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.SaveServerRegEle' at 49;1.", repo.Datastudio.SaveServerRegEleInfo, new RecordItemIndex(25));
            repo.Datastudio.SaveServerRegEle.Click("49;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFYs.hostNameEle' at 399;14.", repo.Datastudio.ContainerFYs.hostNameEleInfo, new RecordItemIndex(26));
            repo.Datastudio.ContainerFYs.hostNameEle.Click("399;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ff' with focus on 'Datastudio.ContainerFYs.hostNameEle'.", repo.Datastudio.ContainerFYs.hostNameEleInfo, new RecordItemIndex(27));
            repo.Datastudio.ContainerFYs.hostNameEle.PressKeys("ff");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFYs.JPanel' at 540;364.", repo.Datastudio.ContainerFYs.JPanelInfo, new RecordItemIndex(28));
            repo.Datastudio.ContainerFYs.JPanel.Click("540;364");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFYs.hostNameEle' at 393;12.", repo.Datastudio.ContainerFYs.hostNameEleInfo, new RecordItemIndex(29));
            repo.Datastudio.ContainerFYs.hostNameEle.Click("393;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFYs.hostNameEle' at 382;13.", repo.Datastudio.ContainerFYs.hostNameEleInfo, new RecordItemIndex(30));
            repo.Datastudio.ContainerFYs.hostNameEle.Click("382;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}' with focus on 'Datastudio.ContainerFYs.hostNameEle'.", repo.Datastudio.ContainerFYs.hostNameEleInfo, new RecordItemIndex(31));
            repo.Datastudio.ContainerFYs.hostNameEle.PressKeys("{Back}{Back}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.ContainerFYs.hostNameEle' at 47;18.", repo.Datastudio.ContainerFYs.hostNameEleInfo, new RecordItemIndex(32));
            repo.Datastudio.ContainerFYs.hostNameEle.Click("47;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+V' Press with focus on 'Datastudio.ContainerFYs.hostNameEle'.", repo.Datastudio.ContainerFYs.hostNameEleInfo, new RecordItemIndex(33));
            Keyboard.PrepareFocus(repo.Datastudio.ContainerFYs.hostNameEle);
            Keyboard.Press(System.Windows.Forms.Keys.V | System.Windows.Forms.Keys.Control, 47, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Datastudio.MountedScripts' at 602;0.", repo.Datastudio.MountedScriptsInfo, new RecordItemIndex(34));
            repo.Datastudio.MountedScripts.Click("602;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(35));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
